#!/usr/bin/env bash

cd /autograder/source

# Copy the student's code into the autograder directory. Make sure
# student has the right package name in their file and that it's in
# the right place
cp /autograder/submission/*.java /autograder/source/src/main/java/gradescope/

for file in /autograder/source/src/main/java/gradescope/*.java; do
  cat /autograder/source/prefix $file >> $file.$$
  mv $file.$$ $file
done

chmod +x gradlew

# Run the test cases
./gradlew test

# Create the json file
python3 make_result.py

# Move the json file
cp /autograder/source/results.json /autograder/results/

# Clean up
rm /autograder/source/results.txt
rm /autograder/source/results.json

rm /autograder/source/src/main/java/gradescope/*.java