/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradescope;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.*;
import java.io.*;

class AppTest {

    @Test 
    public void test1_Score5_Hidden() throws Exception {
        String expected = TestUtil.readFile("src/test/resources/sample.out");
        String actual = TestUtil.runProgram("src/test/resources/sample.in", HelloWorld::main);
        assertEquals(expected, actual);
    }

    @Test
    public void test2_Hidden() throws Exception {
        String expected = TestUtil.readFile("src/test/resources/sample2.out");
        String actual = TestUtil.runProgram("src/test/resources/sample2.in", HelloWorld::main);
        assertEquals(expected, actual);
    }

    @Test
    public void test3() throws Exception {
        String expected = TestUtil.readFile("src/test/resources/sample2.out");
        String actual = TestUtil.runProgram("src/test/resources/sample2.in", HelloWorld::main);
        assertEquals(expected, actual);
    }

    @Test
    public void test4_Score4() throws Exception {
        String expected = TestUtil.readFile("src/test/resources/sample2.out");
        String actual = TestUtil.runProgram("src/test/resources/sample2.in", HelloWorld::main);
        assertEquals(expected, actual);
    }
}
