/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradescope;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.*;
import java.io.*;

class AppTest {

    private String readFile(String path) throws Exception {
        File file = new File(path);
        Scanner sc = new Scanner(file);
        String res = "";

        while (sc.hasNextLine()) {
            res += sc.nextLine() + "\n";
        }

        sc.close();

        return res.strip();
    }

    private interface MainClass {
        void main(String[] args);
    }

    private String runProgram(String inputPath, MainClass main) throws Exception {
        // Save IO streams
        InputStream input = System.in;
        PrintStream output = System.out;

        // Set the new IO streams
        System.setIn(new FileInputStream(inputPath));
        ByteArrayOutputStream myOut = new ByteArrayOutputStream();
        System.setOut(new PrintStream(myOut));

        // Run the program
        String[] args = null;
        main.main(args);

        // Reset the streams
        System.setIn(input);
        System.setOut(output);

        return myOut.toString().strip();
    }

    @Test 
    public void test1_Score5_Hidden() throws Exception {
        String expected = readFile("src/test/resources/sample.out");
        String actual = runProgram("src/test/resources/sample.in", HelloWorld::main);
        assertEquals(expected, actual);
    }

    @Test
    public void test2_Hidden() throws Exception {
        String expected = readFile("src/test/resources/sample2.out");
        String actual = runProgram("src/test/resources/sample2.in", HelloWorld::main);
        assertEquals(expected, actual);
    }

    @Test
    public void test3() throws Exception {
        String expected = readFile("src/test/resources/sample2.out");
        String actual = runProgram("src/test/resources/sample2.in", HelloWorld::main);
        assertEquals(expected, actual);
    }

    @Test
    public void test4_Score4() throws Exception {
        String expected = readFile("src/test/resources/sample2.out");
        String actual = runProgram("src/test/resources/sample2.in", HelloWorld::main);
        assertEquals(expected, actual);
    }
}
